USE MASTER
GO

CREATE LOGIN OGRO 
WITH 
	PASSWORD=N'ABC123@', 
	DEFAULT_DATABASE=[MASTER]
GO

CREATE LOGIN AGNALDO 
WITH 
	PASSWORD=N'AGNALDO',	
	DEFAULT_DATABASE=[MASTER], 
	CHECK_EXPIRATION=OFF, 
	CHECK_POLICY=OFF
GO

CREATE SERVER ROLE [DBAS] 
AUTHORIZATION [JOKER\AGNALDO]

SELECT 
	NAME, 
	PRINCIPAL_ID, 
	TYPE_DESC
FROM 
	SYS.SERVER_PRINCIPALS
WHERE 
	NAME = 'DBAS'

ALTER SERVER ROLE DBAS
ADD MEMBER OGRO

ALTER SERVER ROLE DBAS
ADD MEMBER AGNALDO

SELECT 
	SP2.NAME
FROM 
	SYS.SERVER_ROLE_MEMBERS SRM
	INNER JOIN SYS.SERVER_PRINCIPALS SP 
		ON SRM.ROLE_PRINCIPAL_ID = SP.PRINCIPAL_ID
	INNER JOIN SYS.SERVER_PRINCIPALS SP2 
		ON SRM.MEMBER_PRINCIPAL_ID = SP2.PRINCIPAL_ID
WHERE 
	SP.NAME = 'DBAS'

ALTER SERVER ROLE DBAS
DROP MEMBER OGRO

GRANT ALTER ANY LOGIN TO DBAS

GRANT VIEW SERVER STATE TO DBAS

ALTER SERVER ROLE  DBAS
WITH NAME =  DBA

SELECT 
	SP2.NAME
FROM 
	SYS.SERVER_ROLE_MEMBERS SRM
	INNER JOIN SYS.SERVER_PRINCIPALS SP 
	ON SRM.ROLE_PRINCIPAL_ID = SP.PRINCIPAL_ID
	INNER JOIN SYS.SERVER_PRINCIPALS SP2 
	ON SRM.MEMBER_PRINCIPAL_ID = SP2.PRINCIPAL_ID
WHERE 
	SP.NAME = 'DBA'

SELECT 
	PERMISSION_NAME, 
	STATE_DESC
FROM 
	SYS.SERVER_PERMISSIONS PERM 
	INNER JOIN SYS.SERVER_PRINCIPALS SP 
	ON PERM.GRANTEE_PRINCIPAL_ID = SP.PRINCIPAL_ID
	WHERE SP.NAME = 'DBA'

/* CLEANUP */
DROP LOGIN OGRO
DROP LOGIN AGNALDO
DROP SERVER ROLE DBA
