USE MASTER

IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME='DEMO')
	DROP DATABASE DEMO

CREATE DATABASE DEMO
GO

USE DEMO

CREATE TABLE DBO.PESSOA
(
    ID INT PRIMARY KEY IDENTITY, 
	NOME VARCHAR(50), 
	SEXO CHAR(1)
)

INSERT 
	DBO.PESSOA 
VALUES 
	('ADÃO', 'M'), 
	('EVA', 'F'), 
	('COBRA', '?'), 
	('DERCY', NULL)

BACKUP DATABASE DEMO 
TO DISK = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\DEMO.bak' 
WITH FORMAT, 
	INIT,  
	STATS = 10

INSERT 
	PESSOA
VALUES
	('EPAMINONDAS', 'M'), 
	('CHICA', 'F') 

BACKUP DATABASE DEMO 
TO DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\DEMO.bak' 
WITH NOFORMAT, 
	NOINIT,  
	STATS = 10

RESTORE FILELISTONLY
FROM DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\DEMO.bak' 

RESTORE HEADERONLY
FROM DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\DEMO.bak' 

DBCC CHECKDB WITH PHYSICAL_ONLY

USE MASTER

BACKUP LOG DEMO 
TO DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\DEMO.bak' 
WITH NOFORMAT, 
	NOINIT, 
	NORECOVERY,
	STATS = 5

RESTORE DATABASE DEMO 
PAGE = '1:12' 
FROM DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\DEMO.bak' 
WITH FILE = 1,  
	NORECOVERY,  
	STATS = 5

RESTORE LOG DEMO 
FROM DISK = 'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\Backup\DEMO.bak' 
WITH FILE=3,
	NOUNLOAD,  
	STATS = 5, 
	RECOVERY

USE DEMO

SELECT 
	* 
FROM
	PESSOA

--MOSTRAR RESTORE POINT IN TIME