----------------------------------
--TIPOS DE DADOS
----------------------------------

SELECT 
	CONVERT(TIME, GETDATE()) AS TIME, 
	CONVERT(TIME, GETUTCDATE()) AS TIME_UTC, 
	CONVERT(DATE, GETDATE()) AS DATE, 
	CONVERT(SMALLDATETIME, GETDATE()) AS SMALLDATETIME, 
	CONVERT(DATETIME, GETDATE()) AS DATETIME, 
	CONVERT(DATETIME2, SYSDATETIME()) AS DATETIME2, 
	CONVERT(DATETIME2, SYSUTCDATETIME()) AS DATETIME2_UTC, 
	CONVERT(DATETIMEOFFSET, SYSDATETIMEOFFSET()) AS DATETIMEOFFSET

----------------------------------
--EXTRAIR PARTE OU NOME
----------------------------------

SELECT DATENAME(MM, GETDATE()) AS MES,
	DATENAME(DW, GETDATE()) AS DIA_DA_SEMANA

SELECT DATEPART(YY, SYSDATETIME()) AS ANO,
	DATEPART(M, SYSDATETIME()) AS MES,
	DATEPART(D, SYSDATETIME()) AS DIA,
	DATEPART(HH, SYSDATETIME()) AS HORA,
	DATEPART(N, SYSDATETIME()) AS MINUTO,
	DATEPART(S, SYSDATETIME()) AS SEGUNDO,
	DATEPART(MS, SYSDATETIME()) AS MILISSEGUNDO,
	DATEPART(MCS, SYSDATETIME()) AS MICROSSEGUNDO,
	DATEPART(NS, SYSDATETIME()) AS NANOSSEGUNDO,
	DATEPART(Q, SYSDATETIME()) AS TRIMESTRE,
	DATEPART(ISOWK, SYSDATETIME()) AS SEMANA,
	DATEPART(DY, SYSDATETIME()) AS DIA_DO_ANO, 
	DATEPART(DW, SYSDATETIME()) AS DIA_DA_SEMANA 

----------------------------------
--CRIAR DATA/HORA
----------------------------------

SELECT 
	TIMEFROMPARTS(9, 10, 11, 1, 7) AS TIME, 
	DATEFROMPARTS(2013, 2, 20) AS DATE, 
	SMALLDATETIMEFROMPARTS(2013, 2, 20, 9, 10) AS SMALLDATETIME, 
	DATETIMEFROMPARTS(2013, 2, 20, 9, 10, 11, 1) AS DATETIME, 
	DATETIME2FROMPARTS(2013, 2, 20, 9, 10, 11, 1, 7) AS DATETIME2, 
	DATETIMEOFFSETFROMPARTS(2013, 2, 20, 9, 10, 11, 1, -3, 0, 7) AS DATETIMEOFFSET

----------------------------------
--DIFERENÇA ENTRE DATAS
----------------------------------

SELECT 
	DATEDIFF(YY, DATEFROMPARTS(1966, 9, 12), GETDATE()), 
	DATEDIFF(MM, DATEFROMPARTS(1966, 9, 12), GETDATE()), 
	DATEDIFF(DD, DATEFROMPARTS(1966, 9, 12), GETDATE())

----------------------------------
--MANIPULAÇÃO DE DATAS
----------------------------------

SELECT 
	EOMONTH(GETDATE(), -1) AS ANTERIOR, 
	EOMONTH(GETDATE(), 0) AS ATUAL, 
	EOMONTH(GETDATE(), 1) AS PROXIMO 

DECLARE @D DATETIMEOFFSET = SYSDATETIMEOFFSET()

SELECT
	@D, 
	SWITCHOFFSET(@D, '-01:00'), 
	SWITCHOFFSET(@D, '+00:00'), 
	SWITCHOFFSET(@D, '+03:00')

DECLARE @HOJE DATETIME2 = GETDATE()

SELECT 
	@HOJE, 
	TODATETIMEOFFSET (@HOJE, -60), 
	TODATETIMEOFFSET (@HOJE, -120), 
	TODATETIMEOFFSET (@HOJE, '-03:00') 

----------------------------------
--GET/SET SESSION FORMAT
----------------------------------

SELECT 
	@@DATEFIRST, 
	DATEPART(DW, GETDATE())

SET DATEFIRST 2

SELECT 
	@@DATEFIRST, 
	DATEPART(DW, GETDATE())

SET DATEFIRST 7

SET DATEFORMAT DMY

SELECT 
	CONVERT(DATETIME, '12/02/2013')

SET DATEFORMAT MDY

SELECT 
	CONVERT(DATETIME, '12/02/2013')

SELECT 
	@@LANGUAGE

EXEC SP_HELPLANGUAGE

SET LANGUAGE 'Brazilian'

SELECT 
	1/0

SELECT 
	CONVERT(DATETIME, '12/02/2013')

SELECT 
	DATENAME(DW, GETDATE())

SET LANGUAGE US_ENGLISH

SELECT ISDATE(GETDATE()), ISDATE('BATATINHA')


