USE ADVENTUREWORKS2012

-------------------------------------------
--METADADOS DE STORED PROCEDURES
-------------------------------------------
DECLARE @OBJECTID INT = OBJECT_ID('DBO.USPGETMANAGEREMPLOYEES', 'P')

SELECT * 
FROM SYS.DM_EXEC_DESCRIBE_FIRST_RESULT_SET_FOR_OBJECT(@OBJECTID, 1)

-------------------------------------------
--WITH RESULT SETS
-------------------------------------------

EXEC DBO.USPGETMANAGEREMPLOYEES 205

EXEC DBO.USPGETMANAGEREMPLOYEES 205
WITH RESULT SETS
(
	(
		NIVEL INT, 
		HIERARQUIA NVARCHAR(4000), 
		NOME_GERENTE NAME, 
		SOBRENOME_GERENTE NAME, 
		ID INT, 
		NOME NAME, 
		SOBRENOME NAME
	)
)

