USE ADVENTUREWORKS2012

-----------------------------------
--OVER
-----------------------------------

SELECT TOP 100
	ROW_NUMBER() OVER(PARTITION BY POSTALCODE ORDER BY POSTALCODE) AS 'ROW NUMBER', 
    P.LASTNAME, 
	A.POSTALCODE
FROM 
	PERSON.PERSON AS P 
    INNER JOIN PERSON.ADDRESS AS A 
		ON A.ADDRESSID = P.BUSINESSENTITYID
ORDER BY 
	POSTALCODE

-----------------------------------
--OVER COM AGREGAÇÃO
-----------------------------------

SELECT 
	SALESORDERID, 
	PRODUCTID, 
	ORDERQTY,
    SUM(ORDERQTY) OVER(PARTITION BY SALESORDERID) AS 'TOTAL',
    AVG(ORDERQTY) OVER(PARTITION BY SALESORDERID) AS 'AVG',
    COUNT(ORDERQTY) OVER(PARTITION BY SALESORDERID) AS 'COUNT',
    MIN(ORDERQTY) OVER(PARTITION BY SALESORDERID) AS 'MIN',
    MAX(ORDERQTY) OVER(PARTITION BY SALESORDERID) AS 'MAX'
FROM 
	SALES.SALESORDERDETAIL 
WHERE 
	SALESORDERID IN (43659, 43664)

-----------------------------------
--OVER COM TOTALIZAÇÃO
-----------------------------------

SELECT 
	BUSINESSENTITYID, 
	TERRITORYID, 
	DATEPART(YY, MODIFIEDDATE) AS SALESYEAR,
	CONVERT(VARCHAR(20), SALESYTD, 1) AS SALESYTD,
	CONVERT(VARCHAR(20), AVG(SALESYTD) 
		OVER (PARTITION BY TERRITORYID ORDER BY DATEPART(YY, MODIFIEDDATE)), 1) AS MOVINGAVG,
	CONVERT(VARCHAR(20),SUM(SALESYTD) 
		OVER (PARTITION BY TERRITORYID ORDER BY DATEPART(YY,MODIFIEDDATE)), 1) AS CUMULATIVETOTAL
FROM 
	SALES.SALESPERSON
WHERE 
	TERRITORYID IS NULL 
		OR TERRITORYID < 5
ORDER BY 
	TERRITORYID, 
	SALESYEAR

-----------------------------------
--OVER COM LAG
-----------------------------------

SELECT 
	BUSINESSENTITYID, 
	YEAR(QUOTADATE) AS SALESYEAR, 
	QUOTADATE,
    LAG(SALESQUOTA, 1, 0) 
		OVER (ORDER BY YEAR(QUOTADATE)) AS PREVIOUSQUOTA,
	SALESQUOTA AS CURRENTQUOTA
FROM 
	SALES.SALESPERSONQUOTAHISTORY
WHERE 
	BUSINESSENTITYID = 275 
		AND YEAR(QUOTADATE) IN ('2005', '2006')

-----------------------------------
--OVER COM LEAD
-----------------------------------

SELECT 
	TERRITORYNAME, 
	BUSINESSENTITYID, 
	SALESYTD, 
	LEAD (SALESYTD, 1, 0) 
		OVER (PARTITION BY TERRITORYNAME ORDER BY SALESYTD DESC) AS NEXTREPSALES
FROM 
	SALES.VSALESPERSON
WHERE 
	TERRITORYNAME IN (N'NORTHWEST', N'CANADA') 
ORDER BY 
	TERRITORYNAME

-----------------------------------
--OVER COM PRECEDING
-----------------------------------

SELECT CUSTOMERID, 
        ORDERDATE, 
        SALESORDERNUMBER,
        FIRST_VALUE(ORDERDATE) 
			OVER (PARTITION BY CUSTOMERID ORDER BY ORDERDATE ROWS UNBOUNDED PRECEDING) AS FIRSTORDER
FROM 
	SALES.SALESORDERHEADER
ORDER BY 
	CUSTOMERID, 
	ORDERDATE, 
	SALESORDERNUMBER
